### PR TITLE
Refactor some code to the Official Kotlin codestyle

### PR DESCRIPTION
**Pull request by Zanthed**
Signed-off-by: June <june@eridan.me>

### CODE REVIEW

**Comment by thestinger** [comment]
We're using 100 column width rather than 80 regardless of what the official Kotlin style is so I don't want changes wrapping earlier than that.

**Comment by Zanthed** [comment]
I'll fix that, thanks

**Comment by Zanthed** [comment]
@thestinger The project seems to have already been set to column width 100 by default unless I'm not seeing something you're seeing.

**Comment by quh4gko8** [comment]
> @thestinger The project seems to have already been set to column width 100 by default unless I'm not seeing something you're seeing.

Seems like this is being kicked in for some functions:
https://kotlinlang.org/docs/coding-conventions.html#functions

**Comment by Zanthed** [comment]
Can you specify which function so I can revert the changes?

**Comment by thestinger** [comment]
It's fine then.

**Comment by thestinger** [comment]
@Zanthed needs to be rebased to avoid the conflict with https://github.com/GrapheneOS/Apps/commit/bfff46a0c708f156b6b145574a59cade7047a2ea which will avoid needing that change. You can just drop that change.

**Pull request merged**
